# ≈‰÷√datasource
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.26.178.183:3307/hooc
    username: root
    password: 153500552Mysql.com
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
# ≈‰÷√mybatisªÚmybatis-plus
mybatis-plus:
  type-aliases-package: com.kevin.hooc.common.bean.pojo.entity
  mapper-locations: classpath:mapper/**/*.xml
